POST http://localhost:48003/user
content-type: application/json

{
    "name": "thaylan",
    "email": "thaylan@hotmail.com",
    "password": "123"
}

### 
PUT http://localhost:48003/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDMsImlhdCI6MTczODg4ODEzN30.XL-hq412xtuKGaZzyjKiOhtC4wpGgMobxEyKOclr0Ms

{
    "password": "123",
    "newPassword": "12345"
}

### 
DELETE http://localhost:48003/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDMsImlhdCI6MTczODg4ODEzN30.XL-hq412xtuKGaZzyjKiOhtC4wpGgMobxEyKOclr0Ms

###
POST http://localhost:48003/login
content-type: application/json

{
    "email": "thaylan@hotmail.com",
    "password": "12345"
}
