POST http://localhost:48003/user
content-type: application/json

{
    "name": "talles",
    "email": "talles@hotmail.com",
    "password": "123"
}

### 
PUT http://localhost:48003/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MjM.FQiGUP6OMQOD5zSJLMn_pRQq3nJSRuQmWnEgAhEIm7g

{
    "password": "12345",
    "newPassword": "123"
}

### 
DELETE http://localhost:48003/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MjI.6KqeMwyQ0g0ZVBZZf9lSPF1CxEdaqBA3JdxXswXHGyM


###
POST http://localhost:48003/login
content-type: application/json

{
    "email": "talles@hotmail.com",
    "password": "12003"
}
